-- Migration: 010_user_plants
-- Plant assignments for cross-database IoT gateway access
--
-- Each row links a production user to a gateway plant. The Nhost Function
-- sync-plant-metadata mirrors INSERT/UPDATE to auth.users.metadata.plant_id,
-- which populates the x-hasura-plant-id JWT claim for Remote Schema filtering.
--
-- No FK to gateway.plants — the plants table lives in the gateway's own
-- Postgres database, not in production. Plant IDs are expected to be UUIDs
-- generated by the gateway's Hasura instance.
--
-- RLS: authenticated users can read their own rows only.

CREATE TABLE IF NOT EXISTS public.user_plants (
    user_id      uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    plant_id     uuid        NOT NULL,
    role         text        NOT NULL DEFAULT 'operator'
        CHECK (role IN ('operator', 'supervisor', 'admin')),
    is_primary   boolean     NOT NULL DEFAULT false,
    assigned_at  timestamptz DEFAULT now(),
    assigned_by  uuid        REFERENCES auth.users(id),
    PRIMARY KEY (user_id, plant_id)
);

CREATE INDEX IF NOT EXISTS idx_user_plants_plant ON public.user_plants(plant_id);
CREATE INDEX IF NOT EXISTS idx_user_plants_primary ON public.user_plants(user_id, is_primary)
    WHERE is_primary = true;

COMMENT ON TABLE  public.user_plants IS 'Links production users to gateway plants (N:N)';
COMMENT ON COLUMN public.user_plants.role       IS 'operator | supervisor | admin';
COMMENT ON COLUMN public.user_plants.is_primary  IS 'True if this is the user''s primary plant for JWT claim';
COMMENT ON COLUMN public.user_plants.assigned_at IS 'When this assignment was created';
COMMENT ON COLUMN public.user_plants.assigned_by IS 'Admin who created the assignment (auth.users.id)';

-- ─── RLS ───────────────────────────────────────────────────────────────────────

ALTER TABLE public.user_plants ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_plants_self ON public.user_plants
    FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_plants TO authenticated;

-- ─── Hasura Event Trigger Setup ────────────────────────────────────────────────
-- NOTE: This trigger MUST be created via the Nhost Dashboard after the
--       sync-plant-metadata function is deployed.
--
-- Configuration:
--   Name:              sync_plant_to_metadata
--   Table:             public.user_plants
--   Operations:        INSERT, UPDATE
--   Webhook URL:       {{NHOST_BACKEND_URL}}/v1/functions/sync-plant-metadata
--                      TODO: resolve NHOST_BACKEND_URL (e.g., https://<subdomain>.nhost.run)
--   Headers:
--     x-webhook-secret  →  {{NHOST_WEBHOOK_SECRET}}
--   Retry:             Auto (default)
--
-- After creation, verify with:
--   INSERT INTO public.user_plants (user_id, plant_id, role, is_primary) VALUES
--     ('<test-user-uuid>', '<test-plant-uuid>', 'operator', true);
-- Then check auth.users.metadata.plant_id.
